---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - podAffinityTerm:
      #         labelSelector:
      #           matchLabels:
      #             app: vault
      #         topologyKey: kubernetes.io/hostname
      #       weight: 100
      containers:
      - image: vault:0.11.1
        name: vault
        command:
        - vault
        - server
        - -config
        - /vault/config/config.json
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: VAULT_CLUSTER_ADDR
          value: https://$(POD_IP):8201
        - name: VAULT_REDIRECT_ADDR
          value: https://vault.secret-mgmt.svc.cluster.local:8200
        - name: VAULT_LOG_LEVEL
          value: info
        ports:
        - containerPort: 8200
          name: api
          protocol: TCP
        - containerPort: 8201
          name: cluster-address
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/sys/health?sealedcode=204&standbycode=204&uninitcode=204&
            port: 8200
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /vault/config/
          name: vault-config
        - mountPath: /root/
          name: vault-root
        - mountPath: /etc/tls
          name: consul
      - args:
        - consul
        - agent
        - -advertise=$(POD_IP)
        - -config-file=/consul/config/local.json
        - -retry-join=consul-0.consul.secret-mgmt.svc.cluster.local
        - -retry-join=consul-1.consul.secret-mgmt.svc.cluster.local
        - -retry-join=consul-2.consul.secret-mgmt.svc.cluster.local
        - -encrypt=$(GOSSIP_ENCRYPTION_KEY)
        - -data-dir=/consul/data
        - -disable-host-node-id
        env:
        - name: CONSUL_HTTP_SSL
          value: "true"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: GOSSIP_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: gossip-encryption-key
              name: consul
        - name: CONSUL_LOCAL_CONFIG
          value: '{
            "server": false,
            "datacenter": "dc1",
            "domain": "cluster.local",
            "client_addr": "127.0.0.1",
            "ca_file": "/etc/tls/ca.pem",
            "cert_file": "/etc/tls/consul.pem",
            "key_file": "/etc/tls/consul-key.pem",
            "log_level": "INFO",
            "ca_file": "/etc/tls/ca.pem",
            "cert_file": "/etc/tls/consul.pem",
            "key_file": "/etc/tls/consul-key.pem",
            "verify_incoming": true,
            "verify_outgoing": true,
            "verify_server_hostname": true,
            "ports": {
              "https": 8443
            }
          }'
        image: consul:1.0.3
        imagePullPolicy: IfNotPresent
        name: consul
        volumeMounts:
        - mountPath: /consul/data
          name: consul-data
        - mountPath: /etc/tls
          name: consul
      volumes:
      - configMap:
          defaultMode: 420
          name: vault-config
        name: vault-config
      - emptyDir: {}
        name: vault-root
      - name: consul
        secret:
          defaultMode: 420
          secretName: consul
      - emptyDir: {}
        name: consul-data
